language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

services: docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt --upgrade

before_script:
  - docker-compose -f tests/docker-compose.yml up -d

script: pytest tests/