language: python


python:
  - "3.6"
  - "3.7"
  - "3.8"

services: docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt --upgrade

before_script:
  - docker-compose -f tests/docker-compose.yml up -d

script: pytest tests/

jobs:
  include:
    - stage: "Build and Push Docker Images"
    - services: docker
    - before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - script:
        - docker build -f docker/Dockerfile . -t frater/frater
        - docker build -f docker/GPU.Dockerfile . -t frater/frater:latest-gpu
        - docker push frater/frater
        - docker push frater/frater:latest-gpu
