site_name: Frater
nav:
  - Home: index.md
  - Installation: install.md
  - Getting Started: getting_started.md
  - Examples:
      - Core: examples/core.md
      - Stream: examples/stream.md
      - Task: examples/task.md

  - API:
      - Frater API: api/api.md
      - Core:
          - core: api/core/core.md
          - object: api/core/object.md
      - Stream: api/stream.md
      - Task: api/task.md
      - IO: api/io.md
      - Logging: api/logging.md
      - Validation: api/validation.md
  - About: about.md
theme:
  name: readthedocs