# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/activity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core_dot_core__pb2
from . import object_pb2 as core_dot_object__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/activity.proto',
  package='core',
  syntax='proto3',
  serialized_options=_b('Z\006corepb'),
  serialized_pb=_b('\n\x13\x63ore/activity.proto\x12\x04\x63ore\x1a\x0f\x63ore/core.proto\x1a\x11\x63ore/object.proto\"\xc8\x03\n\x08\x41\x63tivity\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\t\x12\x32\n\ractivity_type\x18\x02 \x01(\x0e\x32\x1b.core.Activity.ActivityType\x12+\n\x0etemporal_range\x18\x03 \x01(\x0b\x32\x13.core.TemporalRange\x12\x14\n\x0csource_video\x18\x04 \x01(\t\x12\x12\n\nexperiment\x18\x05 \x01(\t\x12\x1d\n\x07objects\x18\x06 \x03(\x0b\x32\x0c.core.Object\"\xfc\x01\n\x0c\x41\x63tivityType\x12\x08\n\x04NULL\x10\x00\x12\x08\n\x04TALK\x10\x01\x12\x0e\n\nTALK_PHONE\x10\x02\x12\x0e\n\nTEXT_PHONE\x10\x03\x12\x08\n\x04RIDE\x10\x04\x12\t\n\x05\x43\x41RRY\x10\x05\x12\r\n\tTRANSPORT\x10\x06\x12\x08\n\x04PULL\x10\x07\x12\t\n\x05\x45NTER\x10\x08\x12\x08\n\x04\x45XIT\x10\t\x12\x08\n\x04OPEN\x10\n\x12\t\n\x05\x43LOSE\x10\x0b\x12\x0e\n\nOPEN_TRUNK\x10\x0c\x12\x0f\n\x0b\x43LOSE_TRUNK\x10\r\x12\x08\n\x04LOAD\x10\x0e\x12\n\n\x06UNLOAD\x10\x0f\x12\r\n\tTURN_LEFT\x10\x10\x12\x0e\n\nTURN_RIGHT\x10\x11\x12\n\n\x06U_TURN\x10\x12\x42\x08Z\x06\x63orepbb\x06proto3')
  ,
  dependencies=[core_dot_core__pb2.DESCRIPTOR,core_dot_object__pb2.DESCRIPTOR,])



_ACTIVITY_ACTIVITYTYPE = _descriptor.EnumDescriptor(
  name='ActivityType',
  full_name='core.Activity.ActivityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TALK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TALK_PHONE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT_PHONE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIDE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARRY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULL', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_TRUNK', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_TRUNK', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNLOAD', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN_LEFT', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN_RIGHT', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='U_TURN', index=18, number=18,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=270,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITY_ACTIVITYTYPE)


_ACTIVITY = _descriptor.Descriptor(
  name='Activity',
  full_name='core.Activity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activity_id', full_name='core.Activity.activity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_type', full_name='core.Activity.activity_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temporal_range', full_name='core.Activity.temporal_range', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_video', full_name='core.Activity.source_video', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiment', full_name='core.Activity.experiment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='core.Activity.objects', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIVITY_ACTIVITYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=522,
)

_ACTIVITY.fields_by_name['activity_type'].enum_type = _ACTIVITY_ACTIVITYTYPE
_ACTIVITY.fields_by_name['temporal_range'].message_type = core_dot_core__pb2._TEMPORALRANGE
_ACTIVITY.fields_by_name['objects'].message_type = core_dot_object__pb2._OBJECT
_ACTIVITY_ACTIVITYTYPE.containing_type = _ACTIVITY
DESCRIPTOR.message_types_by_name['Activity'] = _ACTIVITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Activity = _reflection.GeneratedProtocolMessageType('Activity', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVITY,
  __module__ = 'core.activity_pb2'
  # @@protoc_insertion_point(class_scope:core.Activity)
  ))
_sym_db.RegisterMessage(Activity)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
