# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/object.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/object.proto',
  package='core',
  syntax='proto3',
  serialized_options=_b('Z\006corepb'),
  serialized_pb=_b('\n\x11\x63ore/object.proto\x12\x04\x63ore\x1a\x0f\x63ore/core.proto\"\x99\x02\n\x06Object\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12,\n\x0bobject_type\x18\x02 \x01(\x0e\x32\x17.core.Object.ObjectType\x12\x14\n\x0csource_video\x18\x03 \x01(\t\x12\x12\n\nexperiment\x18\x04 \x01(\t\x12$\n\ntrajectory\x18\x05 \x01(\x0b\x32\x10.core.Trajectory\"~\n\nObjectType\x12\x08\n\x04NULL\x10\x00\x12\n\n\x06PERSON\x10\x01\x12\x0b\n\x07VEHICLE\x10\x02\x12\x08\n\x04\x44OOR\x10\x03\x12\x08\n\x04PROP\x10\x04\x12\x11\n\rPULLED_OBJECT\x10\x05\x12\t\n\x05OTHER\x10\x06\x12\x08\n\x04\x42IKE\x10\x07\x12\x11\n\rPARKING_METER\x10\x08\x42\x08Z\x06\x63orepbb\x06proto3')
  ,
  dependencies=[core_dot_core__pb2.DESCRIPTOR,])



_OBJECT_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='core.Object.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERSON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOOR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROP', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULLED_OBJECT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIKE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARKING_METER', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=200,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_OBJECT_OBJECTTYPE)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='core.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='core.Object.object_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_type', full_name='core.Object.object_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_video', full_name='core.Object.source_video', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiment', full_name='core.Object.experiment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajectory', full_name='core.Object.trajectory', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBJECT_OBJECTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=326,
)

_OBJECT.fields_by_name['object_type'].enum_type = _OBJECT_OBJECTTYPE
_OBJECT.fields_by_name['trajectory'].message_type = core_dot_core__pb2._TRAJECTORY
_OBJECT_OBJECTTYPE.containing_type = _OBJECT
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'core.object_pb2'
  # @@protoc_insertion_point(class_scope:core.Object)
  ))
_sym_db.RegisterMessage(Object)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
